<?php
/*
 * // For Creating custom buttons
 * Hide the default buttons
  prevArrow: $(".pp2"),
  nextArrow: $(".nn2"),
*/

$products = $this->getFeaturedProducts();

?>

<h2>Featured products</h2>
<div class="featured-carousel">
<?php Foreach($products as $_product){?>
    <div class="hovereffect"  style="margin: 0 auto;">
        <?php // Product Image ?>
        <a  href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="">
            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
            <?php $_imgSize = 500; ?>
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                 src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_imgSize, $_imgSize); ?>"
                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" style="width: 100%;" />
        </a>

    </div>
<?php } ?>
</div>
<?php  echo Mage::helper('featuredproducts')->featuredLoader(); ?>

