<?php
/*
 * // For Creating custom buttons
 * Hide the default buttons
  prevArrow: $(".pp2"),
  nextArrow: $(".nn2"),
*/

$products = $this->getFeaturedProducts();
$_imgSize = 400;
?>
  
<h2>Featured products</h2>
<div class="featured-carousel">
<?php Foreach($products as $_product){?>
    <div class="ih-item square effect6 from_top_and_bottom">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
            <div class="img">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize, $_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></div>
            <div class="info">
                <h3><?php echo $_product->getName(); ?></h3>
                <p><?php echo Mage::helper('core')->currency($_product->getPrice()); ?></p>

            </div>
        </a>

    </div>

<?php } ?>

</div>

<?php  echo Mage::helper('featuredproducts')->featuredLoader(); ?>

